### ISSUE TITLE
Problem with the CUDA platform

### ISSUE THREAD

**Issue by yaoyic** [peastman/openmm-torch#4]
Hi Peter,

I met with some issues when running this plugin with the `CUDA` simulation platform of OpenMM.

The test script looks like this:
```python
import simtk.openmm as mm
import simtk.unit as unit
import openmmnn as nn

system = mm.System()
for i in range(3):
    system.addParticle(1.0)
f = nn.NeuralNetworkForce('central.pt')
system.addForce(f)
integrator = mm.VerletIntegrator(0.001)
platform = mm.Platform.getPlatformByName('CUDA')
context = mm.Context(system, integrator, platform)
positions = [mm.Vec3(3, 0, 0), mm.Vec3(0, 4, 0), mm.Vec3(3, 4, 0)]
context.setPositions(positions)
print(context.getState(getEnergy=True).getPotentialEnergy())
```
The `central.pt` file comes from `tests/central.pt`.

When running with `CPU` platform, the correct answer was returned; while on the `CUDA` platform, it ended up with this traceback:
```bash
(simu) [yaoyic@yaoyi-pc test-openmm-torch]$ python test_model.py 
Traceback (most recent call last):
  File "test_model.py", line 15, in <module>
    print(context.getState(getEnergy=True).getPotentialEnergy())
  File "/home/yaoyic/miniconda3/envs/simu/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 11060, in getState
    state = _openmm.Context_getState(self, types, enforcePeriodicBox, groups_mask)
Exception: Error invoking kernel: CUDA_ERROR_INVALID_HANDLE (400) 
```

The testing machine comes with an RTX 2060 super, driver version 430.40, CUDA version 10.1.243, openmm version py37_cuda101_rc_1, and libtorch version 1.3.0.

**Comment by peastman** [comment]
See #2.  You need to use the latest OpenMM code from github.

**Comment by yaoyic** [comment]
It is functional with the latest OpenMM code from github. Many thanks!
